module.exports = {
    description: 'Bet you cant say the tongue twister I give you!',
    aliases: ['tt'],
    usage: 'tonguetwister'
}

module.exports.run = async(client, message, args, cmd) => {

    const responses = [
        `Peter Piper picked a peck of pickled peppers`,
        `A peck of pickled peppers Peter Piper picked`,
        `If Peter Piper picked a peck of pickled peppers`,
        `Where’s the peck of pickled peppers Peter Piper picked?`,
        `Betty Botter bought some butter`,
        `But she said the butter’s bitter`,
        `If I put it in my batter, it will make my batter bitter`,
        `But a bit of better butter will make my batter better`,
        `So ‘twas better Betty Botter bought a bit of better butter`,
        `How much wood would a woodchuck chuck if a woodchuck could chuck wood?`,
        `He would chuck, he would, as much as he could, and chuck as much wood`,
        `As a woodchuck would if a woodchuck could chuck wood`,
        `She sells seashells by the seashore`,
        `How can a clam cram in a clean cream can?`,
        `I scream, you scream, we all scream for ice cream`,
        `I saw Susie sitting in a shoeshine shop`,
        `Susie works in a shoeshine shop. Where she shines she sits, and where she sits she shines`,
        `Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn’t fuzzy, was he?`,
        `Can you can a can as a canner can can a can?`,
        `I have got a date at a quarter to eight; I’ll see you at the gate, so don’t be late`,
        `You know New York, you need New York, you know you need unique New York`,
        `I saw a kitten eating chicken in the kitchen`,
        `If a dog chews shoes, whose shoes does he choose?`,
        `I thought I thought of thinking of thanking you`,
        `I wish to wash my Irish wristwatch`,
        `Near an ear, a nearer ear, a nearly eerie ear`,
        `Eddie edited it`,
        `Willie’s really weary`,
        `A big black bear sat on a big black rug`,
        `Tom threw Tim three thumbtacks`,
        `He threw three free throws`,
        `Nine nice night nurses nursing nicely`,
        `So, this is the sushi chef`,
        `Four fine fresh fish for you`,
        `Wayne went to wales to watch walruses`,
        `Six sticky skeletons (x3)`,
        `Which witch is which? (x3)`,
        `Snap crackle pop (x3)`,
        `Flash message (x3)`,
        `Red Buick, blue Buick (x3)`,
        `Red lorry, yellow lorry (x3)`,
        `Thin sticks, thick bricks (x3)`,
        `Stupid superstition (x3)`,
        `Eleven benevolent elephants (x3)`,
        `Two tried and true tridents (x3)`,
        `Rolling red wagons (x3)`,
        `Black back bat (x3)`,
        `She sees cheese (x3)`,
        `Truly rural (x3)`,
        `Good blood, bad blood (x3)`,
        `Pre-shrunk silk shirts (x3)`,
        `Ed had edited it. (x3)`,
        `We surely shall see the sun shine soon`,
        `Which wristwatches are Swiss wristwatches?`,
        `Fred fed Ted bread, and Ted fed Fred bread`,
        `I slit the sheet, the sheet I slit, and on the slitted sheet I sit`,
        `A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk`,
        `Lesser leather never weathered wetter weather better`,
        `Of all the vids I’ve ever viewed, I’ve never viewed a vid as valued as Alex’s engVid vid`,
        `Say ToyBoat (x5)`
    ]

    message.channel.send(new client.embed()
            .setDescription(`**Tongue Twister:** ${responses[~~(Math.random() * responses.length)]}`))
        .setFooter(message.author.username, message.author.displayAvatarURL({ dynamic: true, size: 1024 }))
}